// Objective-C API for talking to ngrok/client Go package.
//   gobind -lang=objc ngrok/client
//
// File is generated by gobind. Do not edit.

#ifndef __Client_H__
#define __Client_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ClientClientMetrics;
@class ClientClientModel;
@class ClientConfiguration;
@class ClientController;
@class ClientOptions;
@class ClientTunnelConfiguration;

@interface ClientClientMetrics : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@end

@interface ClientClientModel : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ClientModel.Logger with unsupported type: ngrok/log.Logger

- (void)addLogPrefix:(NSString* _Nullable)p0;
- (void)clearLogPrefixes;
// skipped method ClientModel.Debug with unsupported parameter or return types

// skipped method ClientModel.Error with unsupported parameter or return types

// skipped method ClientModel.GetBytesInMetrics with unsupported parameter or return types

// skipped method ClientModel.GetBytesOutMetrics with unsupported parameter or return types

- (NSString* _Nonnull)getClientVersion;
// skipped method ClientModel.GetConnStatus with unsupported parameter or return types

// skipped method ClientModel.GetConnectionMetrics with unsupported parameter or return types

// skipped method ClientModel.GetProtocols with unsupported parameter or return types

- (NSString* _Nonnull)getServerVersion;
// skipped method ClientModel.GetTunnels with unsupported parameter or return types

// skipped method ClientModel.GetUpdateStatus with unsupported parameter or return types

// skipped method ClientModel.Info with unsupported parameter or return types

// skipped method ClientModel.PlayRequest with unsupported parameter or return types

- (void)run;
// skipped method ClientModel.SetUpdateStatus with unsupported parameter or return types

- (void)shutdown;
// skipped method ClientModel.Warn with unsupported parameter or return types

@end

@interface ClientConfiguration : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull httpProxy;
@property (nonatomic) NSString* _Nonnull serverAddr;
@property (nonatomic) NSString* _Nonnull inspectAddr;
@property (nonatomic) BOOL trustHostRootCerts;
@property (nonatomic) NSString* _Nonnull authToken;
// skipped field Configuration.Tunnels with unsupported type: map[string]*ngrok/client.TunnelConfiguration

@property (nonatomic) NSString* _Nonnull logTo;
@property (nonatomic) NSString* _Nonnull path;
@end

/**
 * The MVC Controller
 */
@interface ClientController : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * public interface
 */
- (nullable instancetype)init;
// skipped field Controller.Logger with unsupported type: ngrok/log.Logger

- (void)addLogPrefix:(NSString* _Nullable)p0;
// skipped method Controller.AddView with unsupported parameter or return types

- (void)clearLogPrefixes;
// skipped method Controller.Debug with unsupported parameter or return types

// skipped method Controller.Error with unsupported parameter or return types

- (ClientClientModel* _Nullable)getModel;
- (NSString* _Nonnull)getWebInspectAddr;
// skipped method Controller.Go with unsupported parameter or return types

// skipped method Controller.Info with unsupported parameter or return types

// skipped method Controller.PlayRequest with unsupported parameter or return types

- (void)run:(ClientConfiguration* _Nullable)config;
- (ClientClientModel* _Nullable)setupModel:(ClientConfiguration* _Nullable)config;
- (void)shutdown:(NSString* _Nullable)message;
// skipped method Controller.State with unsupported parameter or return types

// skipped method Controller.Update with unsupported parameter or return types

// skipped method Controller.Updates with unsupported parameter or return types

// skipped method Controller.Warn with unsupported parameter or return types

@end

@interface ClientOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface ClientTunnelConfiguration : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull subdomain;
@property (nonatomic) NSString* _Nonnull hostname;
// skipped field TunnelConfiguration.Protocols with unsupported type: map[string]string

@property (nonatomic) NSString* _Nonnull httpAuth;
// skipped field TunnelConfiguration.RemotePort with unsupported type: uint16

@end

FOUNDATION_EXPORT NSString* _Nonnull const ClientBadGateway;

FOUNDATION_EXPORT ClientConfiguration* _Nullable ClientLoadConfiguration(ClientOptions* _Nullable opts, NSError* _Nullable* _Nullable error);

// skipped function LoadTLSConfig with unsupported parameter or return types


FOUNDATION_EXPORT void ClientMain(void);

FOUNDATION_EXPORT ClientClientMetrics* _Nullable ClientNewClientMetrics(void);

/**
 * public interface
 */
FOUNDATION_EXPORT ClientController* _Nullable ClientNewController(void);

FOUNDATION_EXPORT ClientOptions* _Nullable ClientParseArgs(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL ClientSaveAuthToken(NSString* _Nullable configPath, NSString* _Nullable authtoken, NSError* _Nullable* _Nullable error);

#endif
